### ISSUE TITLE
Manual keg capacity tracking

### ISSUE THREAD

**Issue by wojo** [swimmadude66/OnTap#7]
Should track history so we can see trends

**Comment by swimmadude66** [comment]
Not terribly sure there's a super accurate way to do this. However, we do save tap-time and untap-time of each keg, along with size (if we have it). This should allow us to at least look at trends for specific beers e.g. 1/2 barrel of tropicalia = ~6 hours

**Comment by wojo** [comment]
Well guess we keep the whiteboard lol

**Comment by swimmadude66** [comment]
I mean, the only real solution to this is actual tracking. we could hook in to the real tracker with some sort of "I poured ~12 oz" thing, but it does not need its own subsystem
